// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aereal/dynamodb-export-poller/internal/ddb (interfaces: Client)

// Package ddb is a generated GoMock package.
package ddb

import (
	context "context"
	reflect "reflect"

	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DescribeExport mocks base method.
func (m *MockClient) DescribeExport(arg0 context.Context, arg1 *dynamodb.DescribeExportInput, arg2 ...func(*dynamodb.Options)) (*dynamodb.DescribeExportOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeExport", varargs...)
	ret0, _ := ret[0].(*dynamodb.DescribeExportOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeExport indicates an expected call of DescribeExport.
func (mr *MockClientMockRecorder) DescribeExport(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeExport", reflect.TypeOf((*MockClient)(nil).DescribeExport), varargs...)
}

// ListExports mocks base method.
func (m *MockClient) ListExports(arg0 context.Context, arg1 *dynamodb.ListExportsInput, arg2 ...func(*dynamodb.Options)) (*dynamodb.ListExportsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListExports", varargs...)
	ret0, _ := ret[0].(*dynamodb.ListExportsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExports indicates an expected call of ListExports.
func (mr *MockClientMockRecorder) ListExports(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExports", reflect.TypeOf((*MockClient)(nil).ListExports), varargs...)
}
